baseURL: "https://yash-c-nus.github.io/" 
title: Yash Chhabra
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Reads
          url: books/
          weight: 3 
        - name: Coffee
          url: data/
          weight: 5
        - name: Courses
          url: courses/
          weight: 2
        - name: Projects/Competitions
          url: papers/
          weight: 4 
        - name: LinkedIn
          url: https://www.linkedin.com/in/yashc19/
          weight: 6

params:
    description: "MSc Student in Sustainable and Green Finance at NUS Business School | Singapore 

I love breaking down complex problems into simpler components, making it easier to understand and solve them efficiently"

    author: yash chhabra
    googleAnalyticsID: "G6FF6VLVJ7H"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Yash Chhabra
          subtitle: "I'm an MSc student in **Sustainable and Green Finance** at **NUS Business School.** I am also a Graduate Student Researcher at the **Sustainable and Green Finance Institute (SGFIN)**, where I contribute to developing sustainability frameworks."

          <br><br>
          My mom, a former teacher, has an extraordinary talent for breaking down complex ideas into simple, digestible terms, which makes her the best teacher I’ve ever had. This skill of **simplifying complexity** is the same approach I aspire to bring to the world of Sustainability to solve complex problems.
          
          <br><br>
          Actively seeking **Capstone Project** opportunities for **early 2025**, with a focus on applying expertise in Sustainability and Finance to solve complex, real-world challenges. "
          imageUrl: "GitHub.jpg"
          imageWidth: 150
          imageHeight: 150
          imageTitle: Yash Chhabra
          buttons:
            - name: Courses
              url: courses/
            - name: Reads
              url: books/
            - name: Projects/Competitions
              url: papers/
            # name: Reads
             # url: reads/
            - name: Coffee
              url: data/

    socialIcons:
        - name: CV
          url: Yash Chhabra - Resume.pdf
        - name: Email
          url: mailto:yash.c@u.nus.edu
        - name: LinkedIn
          url: https://www.linkedin.com/in/yashc19/

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Yash Chhabra"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
